spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
      auto.register.schemas: true
      use.latest.version: true

grpc:
  server:
    port: 9090

kafka:
  topics:
    sensors: ${KAFKA_TOPIC_SENSORS:telemetry.sensors.v1}
    hubs: ${KAFKA_TOPIC_HUBS:telemetry.hubs.v1}

logging:
  level:
    root: INFO
    ru.yandex.practicum.telemetry: DEBUG
    io.confluent.kafka.serializers: TRACE
    org.apache.avro: TRACE
    org.apache.kafka.clients.producer: INFO
    org.apache.kafka: DEBUG
    io.confluent: DEBUG